/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SelectRouteImport } from './routes/select'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiLogoRouteImport } from './routes/api/logo'
import { Route as ApiGameDetailRouteImport } from './routes/api/game-detail'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoRoute = ApiLogoRouteImport.update({
  id: '/api/logo',
  path: '/api/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameDetailRoute = ApiGameDetailRouteImport.update({
  id: '/api/game-detail',
  path: '/api/game-detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select': typeof SelectRoute
  '/timeline': typeof TimelineRoute
  '/api/game-detail': typeof ApiGameDetailRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select': typeof SelectRoute
  '/timeline': typeof TimelineRoute
  '/api/game-detail': typeof ApiGameDetailRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/select': typeof SelectRoute
  '/timeline': typeof TimelineRoute
  '/api/game-detail': typeof ApiGameDetailRoute
  '/api/logo': typeof ApiLogoRoute
  '/api/og': typeof ApiOgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select'
    | '/timeline'
    | '/api/game-detail'
    | '/api/logo'
    | '/api/og'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select'
    | '/timeline'
    | '/api/game-detail'
    | '/api/logo'
    | '/api/og'
  id:
    | '__root__'
    | '/'
    | '/select'
    | '/timeline'
    | '/api/game-detail'
    | '/api/logo'
    | '/api/og'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectRoute: typeof SelectRoute
  TimelineRoute: typeof TimelineRoute
  ApiGameDetailRoute: typeof ApiGameDetailRoute
  ApiLogoRoute: typeof ApiLogoRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo': {
      id: '/api/logo'
      path: '/api/logo'
      fullPath: '/api/logo'
      preLoaderRoute: typeof ApiLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game-detail': {
      id: '/api/game-detail'
      path: '/api/game-detail'
      fullPath: '/api/game-detail'
      preLoaderRoute: typeof ApiGameDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectRoute: SelectRoute,
  TimelineRoute: TimelineRoute,
  ApiGameDetailRoute: ApiGameDetailRoute,
  ApiLogoRoute: ApiLogoRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
